# Generated by Django 5.2.6 on 2025-11-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0004_remove_jig_jig_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jig',
            name='jig_qr_id',
            field=models.CharField(help_text='Unique Jig QR ID', max_length=100, null=True, unique=True),
        ),
    ]
